"""initial db

Revision ID: 638e26590804
Revises: 
Create Date: 2026-02-24 06:55:27.195288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '638e26590804'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_files',
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='文件的SHA256值'),
    sa.Column('file_path', sa.String(), nullable=False, comment='OSS/S3上的存储路径 key'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件字节大小'),
    sa.Column('total_pages', sa.Integer(), nullable=True, comment='PDF 总页数'),
    sa.Column('task_id', sa.String(length=64), nullable=True, comment='Celery 异步任务 ID'),
    sa.Column('current_page', sa.Integer(), nullable=True, comment='当前已解析到的页码 (用于进度追踪)'),
    sa.Column('process_status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='PDF原生元数据: author, publish_date, doi'),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="每页的物理尺寸 [{'width': w, 'height': h}]"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最后被访问/引用的时间 (用于GC)'),
    sa.PrimaryKeyConstraint('file_hash')
    )
    with op.batch_alter_table('global_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_files_task_id'), ['task_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pdf_formulas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('formula_index', sa.Integer(), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='[x, y, w, h]'),
    sa.Column('latex_content', sa.Text(), nullable=False, comment='LaTeX公式内容'),
    sa.ForeignKeyConstraint(['file_hash'], ['global_files.file_hash'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', 'page_number', 'formula_index', name='uix_formula_loc')
    )
    with op.batch_alter_table('pdf_formulas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pdf_formulas_file_hash'), ['file_hash'], unique=False)

    op.create_table('pdf_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_index', sa.Integer(), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='[x, y, w, h]'),
    sa.Column('image_path', sa.String(), nullable=True, comment='OSS/S3上的存储路径 key'),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['file_hash'], ['global_files.file_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pdf_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pdf_images_file_hash'), ['file_hash'], unique=False)

    op.create_table('pdf_paragraphs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False, comment='该页第几个段落'),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('translation_text', sa.Text(), nullable=True, comment='翻译好的文本(可选)'),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='[x, y, w, h] 归一化坐标'),
    sa.ForeignKeyConstraint(['file_hash'], ['global_files.file_hash'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', 'page_number', 'paragraph_index', name='uix_para_loc')
    )
    with op.batch_alter_table('pdf_paragraphs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pdf_paragraphs_file_hash'), ['file_hash'], unique=False)

    op.create_table('user_graph_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_graph_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_graph_projects_user_id'), ['user_id'], unique=False)

    op.create_table('user_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='用户自定义标题'),
    sa.Column('read_status', sa.String(length=20), nullable=True, comment='阅读状态: unread, reading, finished'),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True, comment='用户标签'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间'),
    sa.ForeignKeyConstraint(['file_hash'], ['global_files.file_hash'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'file_hash', name='uix_user_file')
    )
    with op.batch_alter_table('user_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_papers_user_id'), ['user_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_paper_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_paper_id'], ['user_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('graph_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False, comment="显示的关键词，如 'Transformer'"),
    sa.Column('properties', sa.Text(), nullable=True, comment='JSON string for UI props: color, size, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['user_graph_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'label', name='uix_project_node_label')
    )
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_nodes_project_id'), ['project_id'], unique=False)

    op.create_table('graph_paper_association',
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('user_paper_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['user_graph_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_paper_id'], ['user_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('graph_id', 'user_paper_id')
    )
    op.create_table('user_highlights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_paper_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('rects', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='[{x,y,w,h}, {x,y,w,h}]'),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_paper_id'], ['user_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_highlights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_highlights_user_paper_id'), ['user_paper_id'], unique=False)

    op.create_table('user_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_paper_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True, comment='笔记标题'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True, comment='笔记关键词/标签'),
    sa.ForeignKeyConstraint(['user_paper_id'], ['user_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_notes_user_paper_id'), ['user_paper_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True, comment='具体关系描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['user_graph_projects.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_edges_project_id'), ['project_id'], unique=False)

    op.create_table('note_node_link',
    sa.Column('user_note_id', sa.Integer(), nullable=False),
    sa.Column('graph_node_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['graph_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_note_id'], ['user_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_note_id', 'graph_node_id')
    )
    op.create_table('paper_node_link',
    sa.Column('user_paper_id', sa.UUID(), nullable=False),
    sa.Column('graph_node_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['graph_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_paper_id'], ['user_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_paper_id', 'graph_node_id')
    )
    op.create_table('chat_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_attachments_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_attachments_message_id'))

    op.drop_table('chat_attachments')
    op.drop_table('paper_node_link')
    op.drop_table('note_node_link')
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edges_project_id'))

    op.drop_table('graph_edges')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notes_user_paper_id'))

    op.drop_table('user_notes')
    with op.batch_alter_table('user_highlights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_highlights_user_paper_id'))

    op.drop_table('user_highlights')
    op.drop_table('graph_paper_association')
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_nodes_project_id'))

    op.drop_table('graph_nodes')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('user_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_papers_user_id'))

    op.drop_table('user_papers')
    with op.batch_alter_table('user_graph_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_graph_projects_user_id'))

    op.drop_table('user_graph_projects')
    with op.batch_alter_table('pdf_paragraphs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdf_paragraphs_file_hash'))

    op.drop_table('pdf_paragraphs')
    with op.batch_alter_table('pdf_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdf_images_file_hash'))

    op.drop_table('pdf_images')
    with op.batch_alter_table('pdf_formulas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdf_formulas_file_hash'))

    op.drop_table('pdf_formulas')
    op.drop_table('users')
    with op.batch_alter_table('global_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_files_task_id'))

    op.drop_table('global_files')
    # ### end Alembic commands ###
